import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";

const kanit = Kanit({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gather",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} antialiased`}>
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  );
}
